SET _datetime=%DATE:~7,2%-%DATE:~4,2%-%DATE:~10,4%
ECHO Date: %DATE% 
ECHO Time: %TIME%  
ECHO %_datetime%
REM Created 3d4 91, Rsync ini di design untuk copy file dan dengan umur 2 hari dari pembuatan , skip file ber extentiaon .JPG, simpan log, skip error, dan mutltiple execution.
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sgu\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Sanggau_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-grs\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-grs-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bgr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bgr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-byw\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-byw-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bnj\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bnj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bjg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bjg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-byl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-byl-%_datetime%.log 
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cms\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cms-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cbg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cbg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cbt\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cbt-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cld\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cld-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cmh\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cmh-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cpt\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cpt-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bgn\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Baganbatu_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-blp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Balikpapan_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bjm\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bjm_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bjr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bjr_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bdg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Bandung_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bkl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bkl_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-akp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Aekkanopan_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ant\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Antapani_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-tbi\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-tbi-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-tla\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-tla-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-rpt\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-rpt-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-rbg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-rbg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-srn\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-srn-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pts\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pts-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pdn\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pdn-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pbl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pbl-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pwd\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pwd-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-dmi\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-dmi-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-klt\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-klt-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pti\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pti-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pds\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pds-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-plk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-plk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pbd\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pbd-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-crb\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-crb-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-lmg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-lmg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-smg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-smg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cls\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cls-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-clc\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-clc-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ckp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-ckp-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cslo\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-cslo-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mtp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mtp-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-jbg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-jbg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-kpj\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-kpj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ktp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-ktp-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ant\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-rmn\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-rmn-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-dmg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sby1\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sby2\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-tgr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sdj\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sdj-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-cslo\d$\CABANG_SOLO\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-slo-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sbg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sbg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-tsk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-tsk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-wns\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-wns-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ygy\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-ygy-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pwk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pwk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-rkb\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-rkb-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-sga\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-sga-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-smr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-smr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-srg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-srg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pml\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pml-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-psm\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-psm-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pno\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pno-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ptk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-ptk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pbg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pbg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mdn\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mdn-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mjk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mjk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-psr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-psr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pkl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pkl-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-pku\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-pku-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-lwg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-lwg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-lbp\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-lbp-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mdu\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mdu-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mgl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mgl-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mlg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mlg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-kdr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-kdr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-kdl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-kdl-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-ksr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-ksr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-kds\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-kds-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-kng\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-kng-%_datetime%.log
REM start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bdg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bdg-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-dpk\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-dpk-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-grt\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-grt-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-jbr\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-jbr-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-krw\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-krw-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-mdn2\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-mdn2-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-wtc\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-wtc-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-stg\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Sintang_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-wng\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\Sanggau_%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-tgl\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-tgl-%_datetime%.log
start robocopy \\jkt-fs-svr1\e$\Sharing_From_HO\PolisAsuransi \\svr-bks\d$\Sharing_From_HO\PolisAsuransi /E /MIR /XD *.BIN /R:0 /W:0 /XF *.jpg thumbs.db *.7z *.zip /ETA /X /LOG:C:\Temp-log-asuransi\Log\svr-bks-%_datetime%.log


:eof
exit